osx_image: xcode8.1
language: objective-c
podfile: Podfile
before_install:
- gem install cocoapods
- pod install
script:
- set -o pipefail && xcodebuild test -project Partybus.xcodeproj -scheme Partybus -sdk iphonesimulator -destination "platform=iOS,name=iPhone 6s" ONLY_ACTIVE_ARCH=NO | xcpretty
