language: objective-c
cache: cocoapods
podfile: Podfile
before_install:
- gem install cocoapods
- pod install
script:
- set -o pipefail && xcodebuild test -project Partybus.xcodeproj -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
