language: objective-c
cache: cocoapods
podfile: Podfile
before_install:
- gem install cocoapods
- pod install
script:
- set -o pipefail && xcodebuild test -workspace Partybus.xcworkspace -project Partybus.xcproject -scheme Partybus -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
