osx_image: xcode8.1
language: objective-c
cache: cocoapods
podfile: Podfile
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install
script:
- set -o pipefail && xcodebuild test -workspace Example/Partybus.xcworkspace -scheme Partybus -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
